targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        options:
          # Workers can't be compiled with dartdevc, so use dart2js for the example
          compiler: dart2js
        generate_for:
          - example/web/**
