name: drift_sqlite_async
version: 0.2.5
homepage: https://github.com/powersync-ja/sqlite_async.dart
repository: https://github.com/powersync-ja/sqlite_async.dart
description: Use Drift with a sqlite_async database, allowing both to be used in the same application.

topics:
  - drift
  - sqlite
  - async
  - sql
  - flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  drift: ">=2.28.0 <3.0.0"
  sqlite_async: ^0.12.2

dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ">=2.28.0 <3.0.0"
  glob: ^2.1.2
  lints: ^5.0.0
  sqlite3: ^2.4.0
  test: ^1.25.2
  test_api: ^0.7.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
